<template>
  <div class="container-fluid">
    <div class="row mt-5">
      <div class="col-md-6 offset-3">
        <h3>About Page</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum facere alias enim, fugit amet praesentium aspernatur repellat quasi eum aliquam. Explicabo molestiae, aspernatur nobis eum accusantium vel fuga quos cum quisquam obcaecati in esse assumenda ipsa! Quaerat quo optio soluta dolores saepe accusantium atque iste velit excepturi, repellat voluptates quibusdam obcaecati. Voluptatem porro tenetur iusto distinctio, nemo provident quia minus officia, ea dolorem ratione molestiae, repellendus odit. Amet eaque aperiam ipsam est. At repellat delectus dicta, nihil unde iusto nulla ipsam! Labore ratione fuga commodi, odio iusto accusantium veritatis rem tempore enim similique nesciunt dolores consequuntur minima magni eum quos. 🙂</p>

        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>

        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>
        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>
        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>
        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>
        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>
        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>
        <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo libero aliquam aperiam, labore nulla exercitationem reiciendis quidem inventore natus placeat, quod id animi ipsum laborum modi. Nobis tempore error officia dignissimos nulla repellendus sit accusamus odit impedit possimus dolore quibusdam, fugiat alias nemo vero ex! Aspernatur suscipit illo quas corporis recusandae rem laboriosam iste quasi explicabo ab iusto quod quisquam, veritatis quibusdam quo blanditiis magnam possimus, quis voluptate ea iure maiores quia unde. Totam corporis eius inventore doloribus officiis et modi sit iste nihil officia, a eaque, nam fugiat maxime unde adipisci eos, magnam tempore dolorem error accusamus assumenda molestias.</p>


        
      </div>
    </div>
  </div>
</template>
